# Generated by Django 5.1.6 on 2025-02-20 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_remove_table_capacity_remove_table_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_bestseller',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_new',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.CharField(choices=[('regular', 'Regular'), ('bestseller', 'Bestseller'), ('new', 'New')], default='regular', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='cafe.category'),
        ),
    ]
