# Generated by Django 5.1.6 on 2025-03-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_remove_menuitem_status_remove_order_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='token',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
