# Generated by Django 5.1.6 on 2025-03-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_alter_qrcode_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
