# Generated by Django 5.1.7 on 2025-04-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_orderdetail_gst_amount_orderdetail_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='table_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
