version: '3.8'

services:
  web:
    build: .
    container_name: django_qr_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: cafe_db
      POSTGRES_USER: cafe_user
      POSTGRES_PASSWORD: password123
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
